# Generated by Django 6.0.3 on 2026-03-28 15:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('title', models.TextField()),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('priority', models.IntegerField(blank=True, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('task_type', models.CharField(blank=True, choices=[('user', 'user'), ('recovery', 'recovery')], max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('synced', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['date'], name='idx_tasks_date'), models.Index(fields=['task_type'], name='idx_tasks_type')],
            },
        ),
    ]
