# Generated by Django 6.0.3 on 2026-03-28 15:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.TextField()),
                ('avatar', models.TextField(blank=True)),
                ('timezone', models.TextField(default='UTC')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
